services:
  blog-dev:
    container_name: blog-dev
    build:
      context: ../../.
      target: deps
      args:
        APP_NAME: blog
    profiles: ["dev", "blog"]
    volumes:
      - "../../.:/app"
    ports:
      - 4321:4321
    command: pnpm nx run-many -t dev -p @jonsimeon/blog --parallel
  blog-run:
    container_name: jonsimeon-blog
    build:
      context: ../../.
      args:
        APP_NAME: blog
      target: runtime
    profiles: ["runtime"]
