services:
  resume-dev:
    container_name: resume-dev
    build:
      context: ../../.
      target: deps
      args:
        APP_NAME: resume
    profiles: ["dev", "resume"]
    volumes:
      - "../../.:/app"
    ports:
      - 4321:4321
    command: pnpm nx run-many -t dev -p @jonsimeon/resume --parallel
  resume-run:
    container_name: jonsimeon-resume
    build:
      context: ../../.
      args:
        APP_NAME: resume
      target: runtime
    profiles: ["runtime"]
