services:
  main-dev:
    container_name: main-dev
    build:
      context: ../../.
      target: deps
      args:
        APP_NAME: main
    profiles: ["dev", "main"]
    volumes:
      - "../../.:/app"
    ports:
      - 4321:4321
    command: pnpm nx run-many -t dev -p @jonsimeon/main
  main-run:
    container_name: jonsimeon-main
    build:
      context: ../../.
      args:
        APP_NAME: main
      target: runtime
    profiles: ["runtime"]
